name: robot
channels:
- conda-forge
- defaults
collections:
  -
dependencies:
- python=3.8
- matplotlib
- numpy
- pip
- pip:
  - jsons
  - pyrealsense2==2.50.0.3812
  - pyyaml
  - opencv-python
  - opencv-contrib-python
  - open3d==0.13.0
